version: '2'
services:
  ECL_3rob:
    image: gramaziokohler/ros-createlab
    container_name: ECL_3rob
    environment:
      - ROS_HOSTNAME=ECL_3rob
      - ROS_MASTER_URI=http://ECL_3rob:11311
      - ROS_LANG_DISABLE=genlisp:gennodejs:geneus
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "9090:9090"
    command:
      - roslaunch
      - /root/catkin_ws/scripts/main.launch
      - rrc:=true
      - gui:=true
      - robot_ip_4600:=192.168.0.102 # WAN port, Ethernet Switch
      - robot_ip_7600:=192.168.0.103 # WAN port, Ethernet Switch
    volumes:
      - ./scripts:/root/catkin_ws/scripts
      - ./../../setup/catkin/abb_irb4600_40_255:/root/catkin_ws/src/abb_irb4600_40_255
      - ./../../setup/catkin/abb_irb7600_400_255:/root/catkin_ws/src/abb_irb7600_400_255
      - ./../../setup/catkin/abb_on_axis:/root/catkin_ws/src/abb_on_axis
      - ./../../setup/catkin/princeton_3rob_cell:/root/catkin_ws/src/princeton_3rob_cell
      - ./../../setup/catkin/princeton_3rob_cell_moveit:/root/catkin_ws/src/princeton_3rob_cell_moveit
