name: ecl_robotic_cell
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.10
  - numpy==1.23.3
  - compas_fab==0.27.0
  - compas==1.17.0
  - compas_rrc==1.1.0
  - roslibpy==1.3.0
# prefix: /opt/homebrew/anaconda3/envs/ecl_robotic_cell

