version: '2'
services:
  GT_BAR:
    image: gramaziokohler/ros-noetic-dfab
    container_name: GT_BAR
    environment:
      - ROS_HOSTNAME=GT_BAR
      - ROS_MASTER_URI=http://GT_BAR:11311
      - ROS_LANG_DISABLE=genlisp:gennodejs:geneus
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "9090:9090"
    command:
      - roslaunch
      - /root/catkin_ws/scripts/main.launch
      - rrc:=false
      - gui:=true
      - robot_ip:=192.168.0.102 # WAN port, Ethernet Switch
    volumes:
      - ./scripts:/root/catkin_ws/scripts
      - ./../../setup/catkin/abb_irb6620:/root/catkin_ws/src/abb_irb6620
      - ./../../setup/catkin/bar_lab:/root/catkin_ws/src/bar_lab
      - ./../../setup/catkin/moveit_bar_lab:/root/catkin_ws/src/moveit_bar_lab
