controller_list:
  - name: fake_robot1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_joint_1
      - robot1_joint_2
      - robot1_joint_3
      - robot1_joint_4
      - robot1_joint_5
      - robot1_joint_6
  - name: fake_robot2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2_joint_1
      - robot2_joint_2
      - robot2_joint_3
      - robot2_joint_4
      - robot2_joint_5
      - robot2_joint_6
  - name: fake_robot1_XYZ_controller
    type: $(arg fake_execution_type)
    joints:
      - bridge1_joint_EA_X
      - robot1_joint_EA_Y
      - robot1_joint_EA_Z
      - robot1_joint_1
      - robot1_joint_2
      - robot1_joint_3
      - robot1_joint_4
      - robot1_joint_5
      - robot1_joint_6
  - name: fake_robot2_XYZ_controller
    type: $(arg fake_execution_type)
    joints:
      - bridge2_joint_EA_X
      - robot2_joint_EA_Y
      - robot2_joint_EA_Z
      - robot2_joint_1
      - robot2_joint_2
      - robot2_joint_3
      - robot2_joint_4
      - robot2_joint_5
      - robot2_joint_6
  - name: fake_robot1_YZ_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_joint_EA_Y
      - robot1_joint_EA_Z
      - robot1_joint_1
      - robot1_joint_2
      - robot1_joint_3
      - robot1_joint_4
      - robot1_joint_5
      - robot1_joint_6
  - name: fake_robot2_YZ_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2_joint_EA_Y
      - robot2_joint_EA_Z
      - robot2_joint_1
      - robot2_joint_2
      - robot2_joint_3
      - robot2_joint_4
      - robot2_joint_5
      - robot2_joint_6
initial:  # Define initial robot poses per group
  - group: robot1
    pose: robot1_home
  - group: robot2
    pose: robot2_home
  - group: robot1_XYZ
    pose: robot1_XYZ_home
  - group: robot2_XYZ
    pose: robot2_XYZ
  - group: robot1_YZ
    pose: robot1_YZ_home
  - group: robot2_YZ
    pose: robot2_YZ_home