version: '2'
services:
  createlab:
    image: gramaziokohler/ros-createlab
    container_name: ECL_2rob
    environment:
      - ROS_HOSTNAME=ECL_2rob
      - ROS_MASTER_URI=http://createlab:11311
      - ROS_LANG_DISABLE=genlisp:gennodejs:geneus
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "9090:9090"
    command:
      - roslaunch
      - /root/catkin_ws/scripts/main.launch
      - rrc:=true
      - gui:=true
    volumes:
      - ./scripts:/root/catkin_ws/scripts
      - ./../../setup/catkin/abb_irb4600_40_255:/root/catkin_ws/src/abb_irb4600_40_255
      - ./../../setup/catkin/princeton_2rob_cell:/root/catkin_ws/src/princeton_2rob_cell
      - ./../../setup/catkin/princeton_2rob_cell_moveit:/root/catkin_ws/src/princeton_2rob_cell_moveit
