controller_list:
  - name: fake_robot1_axis_controller
    joints:
      - r1_cart_joint
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_axis_gripper_controller
    joints:
      - r1_cart_joint
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_controller
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_gripper_controller
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot2_axis_controller
    joints:
      - r2_cart_joint
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_axis_gripper_controller
    joints:
      - r2_cart_joint
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_controller
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_gripper_controller
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
initial:  # Define initial robot poses.
  - group: robot1_axis
    pose: home_r1_axis
  - group: robot2_axis
    pose: home_r2_axis