version: '2'
services:
  ECL_7600:
    image: gramaziokohler/ros-noetic-dfab
    container_name: ECL_7600
    environment:
      - ROS_HOSTNAME=ECL_7600
      - ROS_MASTER_URI=http://ECL_7600:11311
      - ROS_LANG_DISABLE=genlisp:gennodejs:geneus
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "9090:9090"
    command:
      - roslaunch
      - /root/catkin_ws/scripts/main.launch
      - rrc:=false
      - gui:=true
      - robot_ip:=192.168.0.103 # WAN port, Ethernet Switch
    volumes:
      - ./scripts:/root/catkin_ws/scripts
      - ./../../setup/catkin/abb_irb7600_400_255:/root/catkin_ws/src/abb_irb7600_400_255
      # - ./../../setup/catkin/abb_resources:/root/catkin_ws/src/abb_resources
      - ./../../setup/catkin/moveit_irb7600:/root/catkin_ws/src/moveit_irb7600
