controller_list:
  - name: fake_robot1_notrack_controller
    type: $(arg fake_execution_type)
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_notrack_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_track_controller
    type: $(arg fake_execution_type)
    joints:
      - r1_cart_joint
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot1_track_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r1_cart_joint
      - r1_joint_1
      - r1_joint_2
      - r1_joint_3
      - r1_joint_4
      - r1_joint_5
      - r1_joint_6
  - name: fake_robot2_notrack_controller
    type: $(arg fake_execution_type)
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_notrack_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_track_controller
    type: $(arg fake_execution_type)
    joints:
      - r2_cart_joint
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot2_track_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r2_cart_joint
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
  - name: fake_robot3_controller
    type: $(arg fake_execution_type)
    joints:
      - r3_joint_1
      - r3_joint_2
      - r3_joint_3
      - r3_joint_4
      - r3_joint_5
      - r3_joint_6
  - name: fake_robot3_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r3_joint_1
      - r3_joint_2
      - r3_joint_3
      - r3_joint_4
      - r3_joint_5
      - r3_joint_6
  - name: fake_robot1_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_robot2_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_robot3_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: robot1_track_gripper
    pose: robot1_home_zero
  - group: robot2_track_gripper
    pose: robot2_home_zero
  - group: robot3_gripper
    pose: robot3_home_zero